name: Main
on: [push]
jobs:
  Build-And-Run-Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.3.10", "4.0.1"]
    env:
      RAILS_ENV: test
      BUNDLE_PATH: vendor/bundle
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: setup app
        run: |
          cd spec/dummy
          bundle exec rails g impressionist -f
          bundle exec rake db:create db:migrate RAILS_ENV=test
      - name: Lint
        run: bundle exec rubocop
      - name: Run Tests
        run: bundle exec rspec
        env:
          COVERAGE: true
      - name: Upload Coverage
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/coverage.json
        if: matrix.ruby == '4.0.1'